[package]
name = "kaitai-expr-lang"
version = "0.1.0"
authors = ["Opal Symes <code@opal.codes>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.4.2"
nom = "5.1"
thiserror = "1.0"
